- hosts: all
  sudo: true
  pre_tasks:
    - name: "Install required packages"
      apt: name={{ item }}
      with_items:
        - git
    - name: Create self-signed SSL cert
      command: openssl req -new -nodes -x509 -subj "/C=CA/ST=Quebec/L=Montreal/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/ssl/server.key -out /etc/ssl/server.crt -extensions v3_ca creates=/etc/ssl/server.crt
  roles:
    # Install MySQL and configure a Drupal database
    - role: ANXS.mysql
      mysql_databases:
        - name: drupal
      mysql_users:
        - name: drupal
          pass: drupal
          host: "%"
    # Install php-fpm
    - role: nbz4live.php-fpm
      php_fpm_apt_packages:
        - php5-fpm
        - php5-mysql
        - php5-gd
      php_fpm_pools:
         - name: www
           user: www-data
           group: www-data
           listen: /var/run/php-fpm.sock
           listen.owner: www-data
           listen.group: www-data
           chdir: /
    # Install php-cli
    - role: pbuyle.php-cli
    # Install composer
    - role: kosssi.composer
    # Install Drush
    - role: pbuyle.drush
      drush_install_mode: composer
      drush_composer_version: "{{ drush_version }}"
      drushrc:
        root: /var/www
    # Install nginx
    - role: pbuyle.nginx
    # Configure nginx to serve Drupal
    - role: pbuyle.nginx-drupal
      nginx_drupal_upload_progress: false
      nginx_drupal_aio: false
      nginx_drupal_flv_streaming: false
      nginx_drupal_mp4_streaming: false
      nginx_drupal_upstream_servers: ["unix:/var/run/php-fpm.sock"]
      nginx_drupal_upstream_backup_servers: ["unix:/var/run/php-fpm.sock"]
      nginx_drupal_microcache: false
      nginx_drupal_sites:
        - file_name: default
          http:
            port: 80
          https:
            port: 443
            certificate: /etc/ssl/server.crt
            certificate_key: /etc/ssl/server.key
          server_name: "{{ nginx.server_name }}"
          root: /var/www
  tasks:
    - name: Add Global composer bin directory to PATH
      lineinfile: dest="{{ drush_composer_user_home.stdout }}/.profile" line="PATH=$PATH:`composer global config bin-dir --absolute`"
